name: BesAir App

on:
    push:
        branches:
            - main
        paths:
            - 'source-code/app/**'

defaults:
    run:
        working-directory: source-code/app

jobs:
    # Lint:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: Setup Node
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '18'
    #               cache: 'npm'
    #               cache-dependency-path: 'package-lock.json'
    #         - run: npm ci
    #         - name: Run linting
    #           run: npm run lint
    # Typecheck:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: Setup Node
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '18'
    #               cache: 'npm'
    #               cache-dependency-path: 'package-lock.json'
    #         - run: npm ci
    #         - name: Run typechecking
    #           run: npm run type-check

    Build-Image:
        runs-on: ubuntu-latest
        # needs: [Lint, Typecheck]
        # if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'
                  cache-dependency-path: 'source-code/app/package-lock.json'
            - run: npm ci
            - name: Build
              run: npm run build
            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@main
              with:
                  path: source-code/app
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and upload Docker image
              run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/bes-air-app:${{ steps.package-version.outputs.current-version }} -t ${{ secrets.DOCKER_USERNAME }}/bes-air-app:latest -f ./Dockerfile --platform=linux/arm64,linux/amd64,linux/arm/v7,linux/arm/v6 -o type=registry .
